source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Movie-App' do
    pod 'Alamofire', '~> 4.5'
    pod 'SDWebImage', '~> 4.0'
    pod 'EZLoadingActivity'
end